default: # default connection
  type: 'postgres'
  host: 'lallah.db.elephantsql.com'
  port: 5432
  username: 'pbcybzaf'
  password: 'k98tNXeL3E303W62xy3Lsxn9Rdr8Yg4i'
  database: 'pbcybzaf'
  entities: ['src/app/entities/*.ts']
  synchronize: false
